export const URL_API = 'https://api.github.com'
export const SEARCH_REPOS_URI = '/search/repositories'
export const REPOS_URI = '/repos'
export const CODE_ERROR_BAD_REQUEST = 400
export const CODE_ERROR_UNPROCESSABLE_ENTITY = 422
export const CODE_ERROR_SERVER = 500
export const CODE_ERROR_NOT_FOUND = 404
export const ERROR_MESSAGE_BAD_REQUEST = 'Oops, looks like this is a bad request. Try something else.'
export const ERROR_MESSAGE_CONNECTIVITY ='Oops, somehting wrong about your internet connectivity. Might want to take a look.'
export const ERROR_MESSAGE_500 = 'Oops, something\'s wrong on Github servers. Try again later.'
export const ERROR_MESSAGE_NOT_FOUND = 'Oops, there is no result for this. Try something else.'
export const ERROR_MESSAGE_DEFAULT = 'Oops, something went wrong, try something else.'
