export const CACHE_TYPE_REPO = 'REPO'
export const CACHE_TYPE_COMMITS = 'COMMITS'
export const CACHE_TYPE_METRICS_USERS_IMPACT = 'METRICS_USERS_IMPACT'
export const CACHE_TYPE_METRICS_TIMELINE_COMMITS = 'METRICS_TIMELINE_COMMITS'
export const CACHE_TYPE_SEARCH = 'SEARCH'
export const CACHE_TYPE_CONTRIBUTORS = 'CONTRIBUTORS'
export const CACHE_DURATION_MINUTE = 10
