const RepositoryConstants = {
  CACHE_TYPE_REPO: 'REPO',
  CACHE_TYPE_COMMITS: 'COMMITS',
  CACHE_TYPE_METRICS_USERS_IMPACT: 'METRICS_USERS_IMPACT',
  CACHE_TYPE_METRICS_TIMELINE_COMMITS: 'METRICS_TIMELINE_COMMITS',
  CACHE_TYPE_SEARCH: 'SEARCH',
  CACHE_TYPE_CONTRIBUTORS: 'CONTRIBUTORS',
  CACHE_DURATION: 10
}

export default RepositoryConstants
